version: '3'
services:
  etcd-0:
    image: quay.io/coreos/etcd:v3.3
    entrypoint: /scripts/etcd_entrypoint.sh
    environment:
      - ETCDCTL_API=3
    hostname: etcd-0
    volumes:
      - ./bin:/scripts/
      - ./certs:/certs
      - /tmp/etcd:/var/lib/etcd

  # Latest Hyperkube tags can be found here:
  # https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/hyperkube?authuser=2&gcrImageListsize=50
  kube-apiserver:
    image: gcr.io/google-containers/hyperkube:v1.12.2
    entrypoint: /scripts/apiserver_entrypoint.sh
    depends_on:
      - etcd-0
    ports:
      - 6443:6443
      - 8080:8080
    volumes:
      - ./bin:/scripts
      - ./certs:/certs
      - ./conf:/conf

  kube-controller-manager:
    image: gcr.io/google-containers/hyperkube:v1.12.2
    command: |
      kube-controller-manager \
        --address=0.0.0.0 \
        --cluster-name=kubernetes \
        --kubeconfig=/conf/kube-controller-manager.yaml \
        --leader-elect=true \
        --v=2
    depends_on:
      - etcd-0
    volumes:
      - ./conf:/conf
      - ./bin:/scripts
